# Generated by Django 5.2.8 on 2025-11-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(default='Acation', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='langauge',
            field=models.CharField(default='hindi', max_length=100),
        ),
    ]
