# Generated by Django 5.2.8 on 2025-11-28 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_langauge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='langauge',
            new_name='language',
        ),
    ]
