# Generated by Django 5.2.8 on 2025-12-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_address',
            field=models.URLField(blank=True, help_text='youtube link for the movies', null=True),
        ),
    ]
