# Generated by Django 5.2.8 on 2025-11-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_genre_movie_langauge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='langauge',
            field=models.CharField(default='English', max_length=100),
        ),
    ]
